version: '3'
services:
  app:
    build: .
    volumes:
      - .:/github.com/kimihito/tohatebu
    environment:
      - GO111MODULE=on
      - PORT=1323
    ports:
      - 1323:1323
    tty: true
    env_file: .env
    stdin_open: true

